Return raw library
adsabs/biblib-service pull request #169
Opened 2023-06-16 17:32 UTC by tjacovich

Gives the user an option in the API to return raw bibcodes from a library instead of the bibcodes returned from `bigquery`

2023-06-22 20:02 UTC, kelockhart requested changes
Let's add a unittest for the `raw_library` option, but otherwise looks good.

2023-06-22 20:02 UTC, kelockhart commented on biblib/views/http_errors.py
> +         'request, or only the raw library was requested.',
Is this text update needed? As far as I can tell, this error is only used within a `if not raw_library` block

2023-06-22 20:02 UTC, kelockhart commented on biblib/views/library_view.py
> +                solr = 'Only the raw library was requested.'
Add a unittest for this `else` block

2023-06-23 20:31 UTC, kelockhart approved these changes
Looks good!

2023-06-23 20:38 UTC, tjacovich commented
Awesome. I'll merge and release today and deploy to `dev` Monday.

2023-06-23 20:39 UTC, merged