adding the notes table and versioning
adsabs/biblib-service pull request #171
Opened 2023-08-16 21:23 UTC by femalves

I would really like your input this. I wrote the model but I'm not sure if it's the best approach. Please, let me know your thoughts. 
I also made some changes to manage.py but I haven't fully reviewed those yet, but feel free to give me some pointers.

2023-10-12 21:33 UTC, kelockhart requested changes
Looking good so far! There are a few minor comments, but overall it's looking pretty solid, and the refactored code is much easier to read. I know I started this review before your latest commits, so you might have addressed some of this already - if so, disregard the comments that don't apply.

2023-10-12 21:33 UTC, kelockhart commented on biblib/views/library_view.py
> +        HTTP GET request that returns all the documents inside a given
Copy/paste error - update text

2023-10-12 21:33 UTC, kelockhart commented on biblib/views/library_view.py
> +        current_app.logger.warning('Library: {0} is private'.format(library_id))
I know this is pre-existing code, but it's weird that it's generating a warning-level log for this - can you downgrade it to info-level?

2023-10-12 21:33 UTC, kelockhart commented on biblib/tests/unit_tests/test_models.py
> +import pytest
Is this leftover from testing? I don't see it in here

2023-10-12 21:33 UTC, kelockhart commented on biblib/tests/unit_tests/test_views.py
> +import json
Leftover from testing?

2023-10-13 19:55 UTC, femalves commented on biblib/manage.py
> +            n_revisions = current_app.config.get('NUMBER_REVISIONS', 7)
Okay. I'll keep that in mind.

2023-10-13 19:56 UTC, femalves commented on biblib/models.py
> +    bibcode = Column(String(50), nullable=False)
Done.

2023-11-08 12:54 UTC, tjacovich requested changes
I think the merge with `timestamp_sort` looks good. Just had a couple of minor comments.

2023-12-02 01:05 UTC, kelockhart requested changes
Sorry this took me so long! I have some high level questions and suggestions, along with a couple more detailed comments. Let's chat about this during our next meeting - a synchronous review will go faster on my part.

2023-12-02 01:05 UTC, kelockhart commented on biblib/views/user_view.py
> +                if (permissions and main_permission in ['owner']) or not permissions:
Where is `permissions` set? I see `permission.permissions` but not just `permissions`, but maybe I'm missing it. Either way, I have some concerns about the `or not permissions` part being lumped in with the `'owner'` permission. Depending on how `permissions` is assigned, either stick the `or not permissions` in the `elif`, or an `else`

2023-12-13 17:53 UTC, tjacovich approved these changes
Looks good to me. Excited to see it in action.

2023-12-14 21:07 UTC, merged